apiVersion: v1
kind: AutoUpdateImageTransformer
metadata:
  name: auto-update-image
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: image-updater
spec:
  targetImgSelector:
    pattern: ^nginx$
  remoteTagSelector:
    pattern: ^1\.(?P<minor>\d+)\.\d+$
    extract: minor
    sort: numerically
    order: desc
